import {ContinentalMotion} from './motion.js';
const $=id=>document.getElementById(id);
const C=window.Cesium;
const snapshots=[{age:300,era:'Late Carboniferous',title:'Pangea comes together'},{age:260,era:'Middle Permian',title:'The supercontinent assembled'},{age:240,era:'Middle Triassic',title:'The age of Pangea'},{age:200,era:'Early Jurassic',title:'A world beginning to separate'},{age:160,era:'Late Jurassic',title:'The continents drift apart'},{age:0,era:'Present day',title:'The world we know'}];
let viewer,currentAge=240,mode='ancient',placesData,paleoPlaces,selectedIndex=null,labels,grid,rotation=false,busy=false,loadId=0,lastAncientAge=240;
const cache=new Map();
let motion,motionPromise,oceanProvider,motionMode=false,playing=false,direction=-1,lastPlaybackTime=0,lastPlaybackUI=0;
function ageText(age){return Number(age.toFixed(1)).toString();}
function eraAt(age){if(age===0)return 'Present day';if(age>=298.9)return 'Late Carboniferous';if(age>=273)return 'Early Permian';if(age>=259.5)return 'Middle Permian';if(age>=251.9)return 'Late Permian';if(age>=247)return 'Early Triassic';if(age>=237)return 'Middle Triassic';if(age>=201.4)return 'Late Triassic';if(age>=174.7)return 'Early Jurassic';if(age>=161.5)return 'Middle Jurassic';if(age>=143.1)return 'Late Jurassic';if(age>=100.5)return 'Early Cretaceous';if(age>=66)return 'Late Cretaceous';if(age>=56)return 'Paleocene';if(age>=33.9)return 'Eocene';if(age>=23.04)return 'Oligocene';if(age>=5.33)return 'Miocene';if(age>=2.58)return 'Pliocene';if(age>=.0117)return 'Pleistocene';return 'Holocene';}
function updatePlaybackControls(){const b=$('time-play');b.textContent=playing?'Ⅱ Pause':'▶ Play';b.setAttribute('aria-label',playing?'Pause continental motion':'Play continental motion');b.setAttribute('aria-pressed',playing);$('time-direction').textContent=direction<0?'Toward today':'Toward the past';$('time-direction').setAttribute('aria-label',direction<0?'Reverse playback toward the past':'Reverse playback toward today');$('motion-note').textContent=motionMode?'Smooth motion · simplified coastlines':'Drag to watch continental drift';}
function stopPlayback(){playing=false;lastPlaybackTime=0;updatePlaybackControls();}
async function ensureMotion(){if(!motionPromise){motionPromise=fetch('data/motion.json').then(r=>{if(!r.ok)throw Error('Motion data unavailable');return r.json();}).then(async data=>{const image=new Image();image.src='assets/modern-satellite.jpg';await image.decode();motion=new ContinentalMotion(C,viewer,data,image);const canvas=document.createElement('canvas');canvas.width=64;canvas.height=32;const ctx=canvas.getContext('2d');ctx.fillStyle='#183644';ctx.fillRect(0,0,64,32);oceanProvider=await C.SingleTileImageryProvider.fromUrl(canvas.toDataURL(),{credit:'Continental motion: Müller et al. (2022), GPlates · Surface illustration / optional NASA Blue Marble projection'});return motion;}).catch(e=>{motionPromise=null;throw e;});}return motionPromise;}
async function enterMotion(age){const id=++loadId;busy=true;$('status').textContent='Preparing continental motion…';try{await ensureMotion();if(id!==loadId)return;viewer.camera.cancelFlight();const position=viewer.camera.positionCartographic;if(position.height<250000)viewer.camera.setView({destination:C.Cartesian3.fromRadians(position.longitude,position.latitude,250000)});viewer.scene.screenSpaceCameraController.minimumZoomDistance=200000;viewer.imageryLayers.removeAll();viewer.imageryLayers.addImageryProvider(oceanProvider);currentAge=age;mode='ancient';motionMode=true;if(age>0)lastAncientAge=age;motion.setSatellite($('project-satellite').checked);motion.setVisible(true);motion.update(age);setLabels();updateUI();updatePlaybackControls();if(selectedIndex!==null)selectPlace(selectedIndex,false);$('status').textContent='';viewer.scene.requestRender();}catch(e){if(id===loadId){stopPlayback();showError('Continental motion could not load. Choose an age button for a detailed snapshot, or try Play again.');}console.error(e);}finally{if(id===loadId)busy=false;}}
function updateMotion(age){currentAge=Math.max(0,Math.min(300,age));if(currentAge>0)lastAncientAge=currentAge;motion.update(currentAge);labels.forEach((label,i)=>{const pos=placeCoordinates(i);label.position=C.Cartesian3.fromDegrees(pos[0],pos[1],100000);});}
function playbackFrame(now){requestAnimationFrame(playbackFrame);if(!motionMode||busy){lastPlaybackTime=0;return;}if(!motion.ready){viewer.scene.requestRender();lastPlaybackTime=0;return;}if(!playing){lastPlaybackTime=0;return;}if(!lastPlaybackTime){lastPlaybackTime=now;return;}const dt=Math.min((now-lastPlaybackTime)/1000,.1);lastPlaybackTime=now;updateMotion(currentAge+direction*dt*Number($('time-speed').value));if(now-lastPlaybackUI>100||currentAge===0||currentAge===300){updateUI();if(selectedIndex!==null)selectPlace(selectedIndex,false);lastPlaybackUI=now;}if(currentAge===0||currentAge===300)stopPlayback();}

const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function showError(message){$('status').textContent=message;}
async function getData(age){if(!cache.has(age)){const request=fetch(`data/coastlines-${age}.json`).then(r=>{if(!r.ok)throw Error('Reconstruction unavailable');return r.json();}).catch(e=>{cache.delete(age);throw e;});cache.set(age,request);}return cache.get(age);}
function home(){viewer.camera.flyTo({destination:C.Cartesian3.fromDegrees(mode==='modern'?15:10,-22,20500000),orientation:{heading:0,pitch:-C.Math.PI_OVER_TWO,roll:0},duration:reduced?0:1.4});}
function updateUI(){
 const exact=snapshots.find(s=>s.age===currentAge),era=eraAt(currentAge),text=ageText(currentAge);
 $('age-hero').textContent=currentAge===0?'Now':text;$('age-readout').innerHTML=currentAge===0?'Today':`${text} <span>Ma</span>`;$('age-hero').nextElementSibling.textContent=currentAge===0?'modern Earth':'million years ago';$('era-label').textContent=era.toUpperCase();$('era-readout').textContent=era;$('timeline-title').textContent=motionMode?'Continents in motion':exact?.title||'Explore deep time';
 $('ancient-button').classList.toggle('active',mode==='ancient');$('modern-button').classList.toggle('active',mode==='modern');$('ancient-button').setAttribute('aria-pressed',mode==='ancient');$('modern-button').setAttribute('aria-pressed',mode==='modern');document.querySelectorAll('.time-step').forEach(b=>{const active=Math.abs(Number(b.dataset.age)-currentAge)<.05;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});
 $('time-scrubber').value=300-currentAge;$('time-scrubber').setAttribute('aria-valuetext',currentAge===0?'Present day':`${text} million years ago`);
 $('data-note').innerHTML=mode==='modern'?'NASA Blue Marble satellite composite.<br>Modern Earth · about 500 m resolution.':motionMode?($('project-satellite').checked?'Modern imagery on moving plates.<br>Not an ancient landscape.':'Modern outlines in motion.<br>Illustrative surface, not ancient land.'):'PALEOMAP ancient geography.<br>Regional estimates · limited local detail.';
 $('era-label').title=mode==='modern'?'Modern satellite imagery':motionMode?'Model rotations with modern outlines':'PALEOMAP reconstructed ancient geography';$('source-credit').textContent=motionMode?'GPlates · Müller et al. (2022)':mode==='modern'?'NASA Blue Marble · GIBS':'Scotese & Wright (2018) · PALEOMAP';$('source-credit').href=motionMode?'https://gwsdoc.gplates.org/models/#muller2022':mode==='modern'?'https://science.nasa.gov/earth/earth-observatory/blue-marble-next-generation/base-topography-bathymetry/':'https://www.earthbyte.org/paleodem-resource-scotese-and-wright-2018/';
 document.querySelector('.intro').innerHTML=currentAge===0?'Our planet, as it looks today.<br>Trace the journey through deep time.':`Step back ${text} million years.<br>Discover a world ${currentAge>=240?'joined together':'in motion'}.`;
 updatePlaybackControls();
}
function placeCoordinates(i){return motionMode?motion.coordinates(i,currentAge,placesData.places):mode==='ancient'?paleoPlaces.coordinates[String(currentAge)][i]:placesData.coordinates[String(currentAge)][i];}
function setLabels(){if(labels)viewer.entities.removeAll();labels=[];if(!placesData)return;placesData.places.forEach((p,i)=>{const pos=placeCoordinates(i);if(!pos||Math.abs(pos[1])>90)return;labels.push(viewer.entities.add({position:C.Cartesian3.fromDegrees(...pos,motionMode?100000:1000),label:{text:p.name.toUpperCase(),font:'11px sans-serif',fillColor:C.Color.fromCssColorString('#e3eccb'),outlineColor:C.Color.fromCssColorString('#102021'),outlineWidth:3,style:C.LabelStyle.FILL_AND_OUTLINE,show:$('labels-toggle').checked,scaleByDistance:new C.NearFarScalar(500000,1.15,25000000,.8),distanceDisplayCondition:new C.DistanceDisplayCondition(0,40000000),disableDepthTestDistance:motionMode?Infinity:0,pixelOffset:new C.Cartesian2(0,-8)}}));});}
function selectPlace(i,fly=true){selectedIndex=i;const p=placesData.places[i],pos=placeCoordinates(i);if(!pos||Math.abs(pos[1])>90){showError('This location is unavailable at this age.');return;}document.querySelectorAll('.place').forEach(b=>b.classList.toggle('selected',Number(b.dataset.index)===i));$('selection-name').textContent=p.name;$('selection-description').textContent=mode==='modern'?`Explore ${p.name} in NASA’s modern satellite imagery.`:p.description;$('selection-coordinates').textContent=`${Math.abs(pos[1]).toFixed(2)}° ${pos[1]<0?'S':'N'} · ${Math.abs(pos[0]).toFixed(2)}° ${pos[0]<0?'W':'E'}`;$('selection').hidden=false;if(fly)viewer.camera.flyTo({destination:C.Cartesian3.fromDegrees(pos[0],pos[1],3200000),duration:reduced?0:1.6});if(fly&&innerWidth<=800){$('explorer').classList.remove('open');$('panel-toggle').setAttribute('aria-expanded','false');}}
async function changeAge(age,newMode='ancient'){
 stopPlayback();const id=++loadId;busy=true;$('status').textContent=newMode==='modern'?'Loading NASA satellite imagery…':`Reconstructing Earth at ${age} Ma…`;
 try{let provider;if(newMode==='modern'){provider=new C.UrlTemplateImageryProvider({url:'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/BlueMarble_ShadedRelief_Bathymetry/default//GoogleMapsCompatible_Level8/{z}/{y}/{x}.jpeg',maximumLevel:8,credit:'NASA Blue Marble · NASA EOSDIS GIBS · GEBCO'});}else{provider=await C.SingleTileImageryProvider.fromUrl(`assets/paleogeography-${age}.jpg`,{credit:'Scotese & Wright (2018) PALEOMAP PaleoDEMs · CC BY 4.0 · Regional estimates'});}if(id!==loadId)return;
 if(motion)motion.setVisible(false);motionMode=false;viewer.scene.screenSpaceCameraController.minimumZoomDistance=1500;viewer.imageryLayers.removeAll();viewer.imageryLayers.addImageryProvider(provider);currentAge=age;mode=newMode;if(age>0)lastAncientAge=age;setLabels();updateUI();if(selectedIndex!==null)selectPlace(selectedIndex,false);document.querySelector('.intro').innerHTML=age===0?'Our planet, as it looks today.<br>Trace the journey through deep time.':`Step back ${age} million years.<br>Discover a world ${age>=240?'joined together':'in motion'}.`;provider.errorEvent.addEventListener(()=>{showError(newMode==='modern'?'NASA imagery could not load. Try Reconstruction or reload the page.':'Some map tiles could not load. Please reload.');});$('status').textContent='';viewer.scene.requestRender();
 }catch(e){if(id===loadId)showError('The globe could not load. Check your connection and reload to try again.');console.error(e);}finally{if(id===loadId)busy=false;}
}
function renderPlaces(){const query=$('search').value.trim().toLowerCase();$('places').replaceChildren();placesData.places.forEach((p,i)=>{if(!p.name.toLowerCase().includes(query))return;const b=document.createElement('button');b.className='place';b.dataset.index=i;b.innerHTML=`<span class="place-number">0${i+1}</span><span class="place-name">${p.name}</span><span class="place-indicator" aria-hidden="true">⌖</span>`;b.classList.toggle('selected',selectedIndex===i);b.onclick=()=>selectPlace(i);$('places').append(b);});if(!$('places').children.length){const p=document.createElement('p');p.className='empty-search';p.textContent='No matching continents.';$('places').append(p);}}
function createGrid(){grid=new C.CustomDataSource('Grid');const material=C.Color.fromCssColorString('#cfe1bb').withAlpha(.16);for(let lon=-180;lon<180;lon+=30){const positions=[];for(let lat=-89;lat<=89;lat+=2)positions.push(C.Cartesian3.fromDegrees(lon,lat,100));grid.entities.add({polyline:{positions,width:1,material,arcType:C.ArcType.NONE}});}for(let lat=-60;lat<=60;lat+=30){const positions=[];for(let lon=-180;lon<=180;lon+=2)positions.push(C.Cartesian3.fromDegrees(lon,lat,100));grid.entities.add({polyline:{positions,width:1,material,arcType:C.ArcType.NONE}});}grid.show=false;viewer.dataSources.add(grid);}
async function init(){
 if(!C){showError('The globe engine could not load. Check your connection and reload.');return;}
 try{C.Ion.defaultAccessToken='';viewer=new C.Viewer('globe',{baseLayer:false,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,animation:false,timeline:false,fullscreenButton:false,infoBox:false,selectionIndicator:false,requestRenderMode:true,maximumRenderTimeChange:Infinity,terrainProvider:new C.EllipsoidTerrainProvider()});
 viewer.scene.backgroundColor=C.Color.fromCssColorString('#080e12');viewer.scene.globe.baseColor=C.Color.fromCssColorString('#183644');viewer.scene.globe.enableLighting=false;viewer.scene.globe.showGroundAtmosphere=false;viewer.scene.skyAtmosphere.show=true;viewer.scene.skyBox.show=false;viewer.scene.sun.show=false;viewer.scene.moon.show=false;viewer.scene.globe.maximumScreenSpaceError=2;viewer.scene.screenSpaceCameraController.minimumZoomDistance=1500;viewer.scene.screenSpaceCameraController.maximumZoomDistance=45000000;viewer.camera.setView({destination:C.Cartesian3.fromDegrees(10,-22,20500000)});
 // Move the planet to the right on desktop, leaving space for the exploration panel.
 function resize(){viewer.camera.frustum.xOffset=0;viewer.resize();viewer.scene.requestRender();}resize();addEventListener('resize',resize);
 const responses=await Promise.all([fetch('data/places.json'),fetch('data/paleo-places.json')]);if(responses.some(r=>!r.ok))throw Error('Place data unavailable');[placesData,paleoPlaces]=await Promise.all(responses.map(r=>r.json()));renderPlaces();createGrid();
 snapshots.forEach(s=>{const b=document.createElement('button');b.className='time-step';b.dataset.age=s.age;b.textContent=s.age===0?'Today':`${s.age} Ma`;b.title=s.era;b.setAttribute('aria-label',s.age===0?'Present day reconstruction':`${s.age} million years ago, ${s.era}`);b.onclick=()=>changeAge(s.age);$('time-buttons').append(b);});
 $('search').addEventListener('input',renderPlaces);$('ancient-button').onclick=()=>{$('project-satellite').checked=false;return changeAge(snapshots.reduce((best,s)=>Math.abs(s.age-lastAncientAge)<Math.abs(best.age-lastAncientAge)?s:best,snapshots[0]).age);};$('modern-button').onclick=()=>changeAge(0,'modern');$('grid-toggle').onchange=()=>{grid.show=$('grid-toggle').checked;viewer.scene.requestRender();};$('labels-toggle').onchange=()=>{labels.forEach(e=>e.label.show=$('labels-toggle').checked);viewer.scene.requestRender();};$('home').onclick=()=>{selectedIndex=null;$('selection').hidden=true;renderPlaces();home();};$('close-selection').onclick=()=>{selectedIndex=null;$('selection').hidden=true;renderPlaces();};$('zoom-in').onclick=()=>{viewer.camera.zoomIn(viewer.camera.positionCartographic.height*.45);viewer.scene.requestRender();};$('zoom-out').onclick=()=>{viewer.camera.zoomOut(viewer.camera.positionCartographic.height*.7);viewer.scene.requestRender();};$('north').onclick=()=>{viewer.camera.setView({orientation:{heading:0,pitch:viewer.camera.pitch,roll:0}});viewer.scene.requestRender();};$('rotate').onclick=()=>{rotation=!rotation;$('rotate').setAttribute('aria-pressed',rotation);viewer.scene.requestRender();};const labelOccluder=new C.EllipsoidalOccluder(viewer.scene.globe.ellipsoid,viewer.camera.positionWC);let last=performance.now();viewer.scene.preRender.addEventListener(()=>{const now=performance.now(),dt=Math.min((now-last)/1000,.1);last=now;if(motionMode&&labels){labelOccluder.cameraPosition=viewer.camera.positionWC;const time=C.JulianDate.now();labels.forEach(label=>{label.label.show=$('labels-toggle').checked&&labelOccluder.isPointVisible(label.position.getValue(time));});}if(rotation){viewer.camera.rotate(C.Cartesian3.UNIT_Z,-dt*.035);viewer.scene.requestRender();}});
 viewer.screenSpaceEventHandler.setInputAction(()=>{if(rotation){rotation=false;$('rotate').setAttribute('aria-pressed','false');}},C.ScreenSpaceEventType.LEFT_DOWN);
 viewer.scene.postRender.addEventListener(()=>{const height=viewer.camera.positionCartographic.height;$('altitude-readout').textContent=`View height ${(height/1000).toLocaleString(undefined,{maximumFractionDigits:0})} km`;});
 const pointer=new C.ScreenSpaceEventHandler(viewer.scene.canvas);pointer.setInputAction(m=>{const p=viewer.camera.pickEllipsoid(m.endPosition,viewer.scene.globe.ellipsoid);if(p){const g=C.Cartographic.fromCartesian(p),lat=C.Math.toDegrees(g.latitude),lon=C.Math.toDegrees(g.longitude);$('coordinate-readout').textContent=`${Math.abs(lat).toFixed(2)}° ${lat<0?'S':'N'}   ${Math.abs(lon).toFixed(2)}° ${lon<0?'W':'E'}`;}},C.ScreenSpaceEventType.MOUSE_MOVE);
 $('time-play').onclick=async()=>{if(playing){stopPlayback();return;}playing=true;updatePlaybackControls();let age=currentAge;if(direction<0&&age<=0)age=300;if(direction>0&&age>=300)age=0;if(!motionMode||age!==currentAge)await enterMotion(age);};
 $('project-satellite').onchange=async()=>{if(motionMode&&!busy){motion.setSatellite($('project-satellite').checked);updateUI();}else{stopPlayback();await enterMotion(currentAge);}};
 $('time-direction').onclick=()=>{direction*=-1;updatePlaybackControls();};
 $('time-scrubber').addEventListener('input',()=>{stopPlayback();const age=300-Number($('time-scrubber').value);if(motionMode&&!busy){updateMotion(age);updateUI();if(selectedIndex!==null)selectPlace(selectedIndex,false);}else enterMotion(age);});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stopPlayback();});
 requestAnimationFrame(playbackFrame);
 await changeAge(240);
 // Expose read-only state for browser verification.
 window.pangea={get age(){return currentAge},get mode(){return mode},get ready(){return !busy},get playing(){return playing},get motion(){return motionMode},get motionReady(){return !!motion?.ready},get direction(){return direction},get motionData(){return motion?.data},get omittedPieces(){return motion?.omittedPieces},viewer};
 }catch(e){console.error(e);showError('3D graphics could not start. Enable WebGL in your browser and reload.');}
}
$('panel-toggle').onclick=()=>{const open=$('explorer').classList.toggle('open');$('panel-toggle').setAttribute('aria-expanded',open);};$('about-button').onclick=()=>$('about-dialog').showModal();$('close-about').onclick=()=>$('about-dialog').close();$('about-dialog').addEventListener('click',e=>{if(e.target===$('about-dialog')){const r=$('about-dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('about-dialog').close();}});
init();
