import {PaleoImageryProvider} from './terrain.js';
const $=id=>document.getElementById(id);
const C=window.Cesium;
const snapshots=[{age:300,era:'Late Carboniferous',title:'Pangea comes together'},{age:260,era:'Middle Permian',title:'The supercontinent assembled'},{age:240,era:'Middle Triassic',title:'The age of Pangea'},{age:200,era:'Early Jurassic',title:'A world beginning to separate'},{age:160,era:'Late Jurassic',title:'The continents drift apart'},{age:0,era:'Present day',title:'The world we know'}];
let viewer,currentAge=240,mode='ancient',placesData,selectedIndex=null,labels,grid,rotation=false,busy=false,loadId=0,lastAncientAge=240;
const cache=new Map();
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function showError(message){$('status').textContent=message;}
async function getData(age){if(!cache.has(age)){const request=fetch(`data/coastlines-${age}.json`).then(r=>{if(!r.ok)throw Error('Reconstruction unavailable');return r.json();}).catch(e=>{cache.delete(age);throw e;});cache.set(age,request);}return cache.get(age);}
function home(){viewer.camera.flyTo({destination:C.Cartesian3.fromDegrees(mode==='modern'?15:10,-22,20500000),orientation:{heading:0,pitch:-C.Math.PI_OVER_TWO,roll:0},duration:reduced?0:1.4});}
function updateUI(){const s=snapshots.find(s=>s.age===currentAge);$('age-hero').textContent=currentAge===0?'Now':currentAge;$('age-readout').innerHTML=currentAge===0?'Today':`${currentAge} <span>Ma</span>`;$('age-hero').nextElementSibling.textContent=currentAge===0?'modern Earth':'million years ago';$('era-label').textContent=s.era.toUpperCase();$('era-readout').textContent=s.era;$('timeline-title').textContent=s.title;$('ancient-button').classList.toggle('active',mode==='ancient');$('modern-button').classList.toggle('active',mode==='modern');$('ancient-button').setAttribute('aria-pressed',mode==='ancient');$('modern-button').setAttribute('aria-pressed',mode==='modern');document.querySelectorAll('.time-step').forEach(b=>{const active=Number(b.dataset.age)===currentAge;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});$('data-note').innerHTML=mode==='modern'?'NASA Blue Marble satellite composite.<br>Modern Earth · about 500 m resolution.':'Model-based continental positions.<br>Surface texture is illustrative.';$('era-label').title=mode==='modern'?'Modern satellite imagery':'Scientific positions with illustrative surface';}
function placeCoordinates(i){return placesData.coordinates[String(currentAge)][i];}
function setLabels(){if(labels)viewer.entities.removeAll();labels=[];if(!placesData)return;placesData.places.forEach((p,i)=>{const pos=placeCoordinates(i);if(!pos||Math.abs(pos[1])>90)return;labels.push(viewer.entities.add({position:C.Cartesian3.fromDegrees(...pos,1000),label:{text:p.name.toUpperCase(),font:'11px sans-serif',fillColor:C.Color.fromCssColorString('#e3eccb'),outlineColor:C.Color.fromCssColorString('#102021'),outlineWidth:3,style:C.LabelStyle.FILL_AND_OUTLINE,show:$('labels-toggle').checked,scaleByDistance:new C.NearFarScalar(500000,1.15,25000000,.8),distanceDisplayCondition:new C.DistanceDisplayCondition(0,40000000),disableDepthTestDistance:0,pixelOffset:new C.Cartesian2(0,-8)}}));});}
function selectPlace(i,fly=true){selectedIndex=i;const p=placesData.places[i],pos=placeCoordinates(i);if(!pos||Math.abs(pos[1])>90){showError('This location is unavailable at this age.');return;}document.querySelectorAll('.place').forEach(b=>b.classList.toggle('selected',Number(b.dataset.index)===i));$('selection-name').textContent=p.name;$('selection-description').textContent=mode==='modern'?`Explore ${p.name} in NASA’s modern satellite imagery.`:p.description;$('selection-coordinates').textContent=`${Math.abs(pos[1]).toFixed(2)}° ${pos[1]<0?'S':'N'} · ${Math.abs(pos[0]).toFixed(2)}° ${pos[0]<0?'W':'E'}`;$('selection').hidden=false;if(fly)viewer.camera.flyTo({destination:C.Cartesian3.fromDegrees(pos[0],pos[1],3200000),duration:reduced?0:1.6});if(innerWidth<=800){$('explorer').classList.remove('open');$('panel-toggle').setAttribute('aria-expanded','false');}}
async function changeAge(age,newMode='ancient'){
 const id=++loadId;busy=true;$('status').textContent=newMode==='modern'?'Loading NASA satellite imagery…':`Reconstructing Earth at ${age} Ma…`;
 try{let provider;if(newMode==='modern'){provider=new C.UrlTemplateImageryProvider({url:'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/BlueMarble_ShadedRelief_Bathymetry/default//GoogleMapsCompatible_Level8/{z}/{y}/{x}.jpeg',maximumLevel:8,credit:'NASA Blue Marble · NASA EOSDIS GIBS · GEBCO'});}else{provider=new PaleoImageryProvider(C,await getData(age));}if(id!==loadId)return;
 viewer.imageryLayers.removeAll();viewer.imageryLayers.addImageryProvider(provider);currentAge=age;mode=newMode;if(age>0)lastAncientAge=age;setLabels();updateUI();if(selectedIndex!==null)selectPlace(selectedIndex,false);document.querySelector('.intro').innerHTML=age===0?'Our planet, as it looks today.<br>Trace the journey through deep time.':`Step back ${age} million years.<br>Discover a world ${age>=240?'joined together':'in motion'}.`;provider.errorEvent.addEventListener(()=>{showError(newMode==='modern'?'NASA imagery could not load. Try Reconstruction or reload the page.':'Some map tiles could not load. Please reload.');});$('status').textContent='';viewer.scene.requestRender();
 }catch(e){if(id===loadId)showError('The globe could not load. Check your connection and reload to try again.');console.error(e);}finally{if(id===loadId)busy=false;}
}
function renderPlaces(){const query=$('search').value.trim().toLowerCase();$('places').replaceChildren();placesData.places.forEach((p,i)=>{if(!p.name.toLowerCase().includes(query))return;const b=document.createElement('button');b.className='place';b.dataset.index=i;b.innerHTML=`<span class="place-number">0${i+1}</span><span class="place-name">${p.name}</span><span class="place-indicator" aria-hidden="true">⌖</span>`;b.classList.toggle('selected',selectedIndex===i);b.onclick=()=>selectPlace(i);$('places').append(b);});if(!$('places').children.length){const p=document.createElement('p');p.className='empty-search';p.textContent='No matching continents.';$('places').append(p);}}
function createGrid(){grid=new C.CustomDataSource('Grid');const material=C.Color.fromCssColorString('#cfe1bb').withAlpha(.16);for(let lon=-180;lon<180;lon+=30){const positions=[];for(let lat=-89;lat<=89;lat+=2)positions.push(C.Cartesian3.fromDegrees(lon,lat,100));grid.entities.add({polyline:{positions,width:1,material,arcType:C.ArcType.NONE}});}for(let lat=-60;lat<=60;lat+=30){const positions=[];for(let lon=-180;lon<=180;lon+=2)positions.push(C.Cartesian3.fromDegrees(lon,lat,100));grid.entities.add({polyline:{positions,width:1,material,arcType:C.ArcType.NONE}});}grid.show=false;viewer.dataSources.add(grid);}
async function init(){
 if(!C){showError('The globe engine could not load. Check your connection and reload.');return;}
 try{C.Ion.defaultAccessToken='';viewer=new C.Viewer('globe',{baseLayer:false,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,animation:false,timeline:false,fullscreenButton:false,infoBox:false,selectionIndicator:false,requestRenderMode:true,maximumRenderTimeChange:Infinity,terrainProvider:new C.EllipsoidTerrainProvider()});
 viewer.scene.backgroundColor=C.Color.fromCssColorString('#080e12');viewer.scene.globe.baseColor=C.Color.fromCssColorString('#183644');viewer.scene.globe.enableLighting=false;viewer.scene.globe.showGroundAtmosphere=false;viewer.scene.skyAtmosphere.show=true;viewer.scene.skyBox.show=false;viewer.scene.sun.show=false;viewer.scene.moon.show=false;viewer.scene.globe.maximumScreenSpaceError=2;viewer.scene.screenSpaceCameraController.minimumZoomDistance=1500;viewer.scene.screenSpaceCameraController.maximumZoomDistance=45000000;viewer.camera.setView({destination:C.Cartesian3.fromDegrees(10,-22,20500000)});
 // Move the planet to the right on desktop, leaving space for the exploration panel.
 function resize(){viewer.camera.frustum.xOffset=0;viewer.resize();viewer.scene.requestRender();}resize();addEventListener('resize',resize);
 const r=await fetch('data/places.json');if(!r.ok)throw Error('Place data unavailable');placesData=await r.json();renderPlaces();createGrid();
 snapshots.forEach(s=>{const b=document.createElement('button');b.className='time-step';b.dataset.age=s.age;b.textContent=s.age===0?'Today':`${s.age} Ma`;b.title=s.era;b.setAttribute('aria-label',s.age===0?'Present day reconstruction':`${s.age} million years ago, ${s.era}`);b.onclick=()=>changeAge(s.age);$('time-buttons').append(b);});
 $('search').addEventListener('input',renderPlaces);$('ancient-button').onclick=()=>changeAge(lastAncientAge);$('modern-button').onclick=()=>changeAge(0,'modern');$('grid-toggle').onchange=()=>{grid.show=$('grid-toggle').checked;viewer.scene.requestRender();};$('labels-toggle').onchange=()=>{labels.forEach(e=>e.label.show=$('labels-toggle').checked);viewer.scene.requestRender();};$('home').onclick=()=>{selectedIndex=null;$('selection').hidden=true;renderPlaces();home();};$('close-selection').onclick=()=>{selectedIndex=null;$('selection').hidden=true;renderPlaces();};$('zoom-in').onclick=()=>{viewer.camera.zoomIn(viewer.camera.positionCartographic.height*.45);viewer.scene.requestRender();};$('zoom-out').onclick=()=>{viewer.camera.zoomOut(viewer.camera.positionCartographic.height*.7);viewer.scene.requestRender();};$('north').onclick=()=>{viewer.camera.setView({orientation:{heading:0,pitch:viewer.camera.pitch,roll:0}});viewer.scene.requestRender();};$('rotate').onclick=()=>{rotation=!rotation;$('rotate').setAttribute('aria-pressed',rotation);viewer.scene.requestRender();};let last=performance.now();viewer.scene.preRender.addEventListener(()=>{const now=performance.now(),dt=Math.min((now-last)/1000,.1);last=now;if(rotation){viewer.camera.rotate(C.Cartesian3.UNIT_Z,-dt*.035);viewer.scene.requestRender();}});
 viewer.screenSpaceEventHandler.setInputAction(()=>{if(rotation){rotation=false;$('rotate').setAttribute('aria-pressed','false');}},C.ScreenSpaceEventType.LEFT_DOWN);
 viewer.scene.postRender.addEventListener(()=>{const height=viewer.camera.positionCartographic.height;$('altitude-readout').textContent=`View height ${(height/1000).toLocaleString(undefined,{maximumFractionDigits:0})} km`;});
 const pointer=new C.ScreenSpaceEventHandler(viewer.scene.canvas);pointer.setInputAction(m=>{const p=viewer.camera.pickEllipsoid(m.endPosition,viewer.scene.globe.ellipsoid);if(p){const g=C.Cartographic.fromCartesian(p),lat=C.Math.toDegrees(g.latitude),lon=C.Math.toDegrees(g.longitude);$('coordinate-readout').textContent=`${Math.abs(lat).toFixed(2)}° ${lat<0?'S':'N'}   ${Math.abs(lon).toFixed(2)}° ${lon<0?'W':'E'}`;}},C.ScreenSpaceEventType.MOUSE_MOVE);
 await changeAge(240);
 // Expose read-only state for browser verification.
 window.pangea={get age(){return currentAge},get mode(){return mode},get ready(){return !busy},viewer};
 }catch(e){console.error(e);showError('3D graphics could not start. Enable WebGL in your browser and reload.');}
}
$('panel-toggle').onclick=()=>{const open=$('explorer').classList.toggle('open');$('panel-toggle').setAttribute('aria-expanded',open);};$('about-button').onclick=()=>$('about-dialog').showModal();$('close-about').onclick=()=>$('about-dialog').close();$('about-dialog').addEventListener('click',e=>{if(e.target===$('about-dialog')){const r=$('about-dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('about-dialog').close();}});
init();
